// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MvcVeve.Data;

#nullable disable

namespace Carrosserie_Veve.Migrations
{
    [DbContext(typeof(MvcVeveContext))]
    partial class MvcVeveContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.4");

            modelBuilder.Entity("MvcVeve.Models.Horaire", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("HeureDebut")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("HeureFin")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("JourOff")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Vacances")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Horaires");
                });

            modelBuilder.Entity("MvcVeve.Models.Prestation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description_courte")
                        .HasColumnType("TEXT");

                    b.Property<string>("NomPrestation")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("URLImage")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Prestations");
                });

            modelBuilder.Entity("MvcVeve.Models.Realisation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("ImageAp")
                        .HasColumnType("TEXT");

                    b.Property<string>("ImageAvt")
                        .HasColumnType("TEXT");

                    b.Property<string>("NomRealisation")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Realisations");
                });
#pragma warning restore 612, 618
        }
    }
}
